name: Tests
on:
  push:
    branches:
      - master
      - staging
      - trying
  pull_request:
    branches:
      - 'master'
      - 'stable/**'
jobs:
  test_cxxbridge:
    name: Test cxxbridge integration
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os:
          - windows-2019
          - ubuntu-20.04
          - ubuntu-18.04
          - macos-12
        include:
          - abi: default
        #  - os: windows-2019
        #    abi: gnu
    steps:
      - uses: actions/checkout@v3
      - uses: actions/cache@v3
        id: cache_cxxbridge
        with:
          path: "~/.cargo/bin/cxxbridge*"
          key: ${{ runner.os }}-cxxbridge_1_0_86
      - name: Install cxxbridge
        if: steps.cache_cxxbridge.outputs.cache-hit != 'true'
        run: cargo install cxxbridge-cmd@1.0.86
      - name: Install lld
        run: sudo apt update && sudo apt install -y lld
        if: ${{ 'Linux' == runner.os }}
      - name: Setup Environment and Configure CMake
        uses: "./.github/actions/setup_test"
        with:
          target_arch: x86_64
          cmake: 3.15.7
          rust: stable minus 2 releases
          abi: ${{ matrix.abi }}
          generator: ninja
          build_dir: build
          configure_params: -DCORROSION_TESTS_CXXBRIDGE=ON
      - name: Run Tests
        working-directory: build
        run: ctest --output-on-failure --build-config Debug -j 3 -R "^cxxbridge"
