name: Tests
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - '**'
jobs:
  test:
    name: Test Corrosion
    runs-on: ${{ matrix.os }}
    continue-on-error: ${{ matrix.rust == 'nightly' }}
    strategy:
      fail-fast: false
      matrix:
        os:
          - windows-2019 # windows-latest is currently not having a supported MSVC compiler
          - ubuntu-latest
          - macos-12
        arch:
          - x86_64
          - i686
          - aarch64
          - powerpc64le
        abi:
          - gnu
          - darwin
          - msvc
        cmake:
          - 3.15.7
          - 3.19.0
        rust:
          - 1.46.0 # MSRV Minimum supported rust version
          - 1.54.0 # MSRV macos-12
          - stable
        generator:
          - default # This is just whatever the platform default is
          - ninja

        include:
          - rust: nightly
            cmake: 3.19.0
            generator: ninja
            arch: x86_64
            abi: msvc
            os: windows-2019
          - rust: nightly
            cmake: 3.19.0
            generator: ninja
            arch: x86_64
            abi: gnu
            os: ubuntu-latest
          - rust: nightly
            cmake: 3.19.0
            generator: ninja
            arch: x86_64
            abi: darwin
            os: macos-12
          - os: ubuntu-latest
            arch: x86_64
            abi: gnu
            cmake: 3.20.0
            rust: stable
            generator: ninja-multiconfig
          - os: windows-2022
            arch: aarch64
            abi: msvc
            cmake: 3.21.5 # Earliest supported version for VS 17 in windows-2022
            rust: "1.54" # Minimum supported rust version for cross-compile with Windows MSVC
            generator: default
          - os: windows-2022
            arch: i686
            abi: msvc
            cmake: 3.21.5 # Earliest supported version for VS 17 in windows-2022
            rust: "1.54" # Minimum supported rust version for cross-compile with Windows MSVC
            generator: default

        exclude:

          # You cannot build with GNU using Visual Studio on Windows
          - os: windows-2019
            abi: gnu
            generator: default # Default generator is Visual Studio

          # ARCH
          - os: windows-2019
            arch: i686
            abi: gnu
          - os: windows-2019
            arch: aarch64
            abi: gnu
          - os: windows-2019
            arch: i686
            generator: ninja
          - os: windows-2019
            arch: aarch64
            generator: ninja
          - os: windows-2019
            arch: powerpc64le
          - os: macos-12
            arch: i686
          - os: macos-12
            arch: aarch64
          - os: macos-12
            arch: powerpc64le

          # Cross-compiling is broken on Windows with MSVC before 1.54, since build-scripts are cross-linked instead
          # of being linked for the host platform.
          - os: windows-2019
            abi: msvc
            rust: 1.46.0
            arch: i686
          - os: windows-2019
            abi: msvc
            rust: 1.46.0
            arch: aarch64
          - os: windows-2022
            abi: msvc
            rust: 1.46.0
            arch: i686
          - os: windows-2022
            abi: msvc
            rust: 1.46.0
            arch: aarch64

          # ABI
          - os: ubuntu-latest
            abi: msvc
          - os: ubuntu-latest
            abi: darwin
          - os: windows-2019
            abi: darwin
          - os: macos-12
            abi: msvc
          - os: macos-12
            abi: gnu

          # Rust:
          - rust: 1.46.0
            os: macos-12
          - rust: 1.54.0
            os: windows-2019
            abi: gnu
          - rust: 1.54.0
            os: windows-2019
            abi: msvc
            arch: x86_64
          - rust: 1.54.0
            os: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Setup Environment and Configure CMake
        uses: "./.github/actions/setup_test"
        with:
          target_arch: ${{matrix.arch}}
          abi: ${{matrix.abi}}
          cmake: ${{matrix.cmake}}
          rust: ${{matrix.rust}}
          generator: ${{matrix.generator}}
          build_dir: build
      - name: Run Tests
        working-directory: build
        run: ctest --verbose --build-config Debug

  test_cxxbridge:
    name: Test cxxbridge integration
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os:
          - windows-2019
          - ubuntu-latest
          - macos-12
        include:
          - rust: 1.46.0
          - os: macos-12
            rust: 1.54.0  # On MacOS-12 linking fails before Rust 1.54
          - os: macos-12
            abi: darwin
          - os: ubuntu-latest
            abi: gnu
          - os: windows
            abi: msvc
    steps:
      - uses: actions/checkout@v3
      - name: Install cxxbridge
        run: cargo install cxxbridge-cmd@1.0.80
      - name: Setup Environment and Configure CMake
        uses: "./.github/actions/setup_test"
        with:
          target_arch: x86_64
          abi: ${{matrix.abi}}
          cmake: 3.15.7
          rust: ${{matrix.rust}}
          generator: ninja
          build_dir: build
          configure_params: -DCORROSION_TESTS_CXXBRIDGE=ON
      - name: Run Tests
        working-directory: build
        run: ctest --verbose --build-config Debug
  install:
    name: Test Corrosion as a Library
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os:
          - windows-2019
          - ubuntu-latest
          - macos-12
        include:
          - rust: 1.46.0
          - os: macos-12
            rust: 1.54.0  # On MacOS-12 linking fails before Rust 1.54
    steps:
      - uses: actions/checkout@v3
      - name: Setup MSVC Development Environment
        uses: ilammy/msvc-dev-cmd@v1
        if: runner.os == 'Windows'
      - name: Install CMake
        uses: corrosion-rs/install-cmake@v2
        with:
          cmake: 3.18.0
          ninja: 1.10.0
      - name: Install Rust
        uses: dtolnay/rust-toolchain@master
        with:
          toolchain: ${{matrix.rust}}
      - name: CMake Version
        run: cmake --version
      - name: Rust Version
        run: rustc --version
      - name: Test Corrosion as subdirectory
        run: >
          cmake
          -S.
          -Bbuild
          -DCORROSION_VERBOSE_OUTPUT=ON
          -DCORROSION_TESTS_INSTALL_CORROSION=OFF

          cd build

          ctest --output-on-failure -C Debug
      - name: Test Corrosion as installed module
        run: >
          cmake -E remove_directory build

          cmake
          -S.
          -Bbuild
          -DCORROSION_VERBOSE_OUTPUT=ON
          -DCMAKE_BUILD_TYPE=Release
          -DCORROSION_TESTS_INSTALL_CORROSION=ON

          cd build

          ctest --output-on-failure -C Release
